windows_build:
  docker_builder:
    platform: windows
    build_script: docker build -t mpromonet/dockertest:windows . -f Dockerfile.windows

linux_build:    
  docker_builder:
    build_script: docker build -t mpromonet/dockertest:linux . -f Dockerfile.linux
