windows_docker_builder:
  platform: windows
  os_version: 2019
  env:
    DOCKERHUB_USER: ENCRYPTED[80c86842f51e89eebd33a709eda8406f47194be550338b4eb04ac307c03c67b1f30bbc82032f58aeb86dbc0f1e8752ff]
    DOCKERHUB_PASS: ENCRYPTED[8c8912da52400d309e2fb75444639dfe774b210feaa5f1701e7a3f6e37959971ba41f9e5845c77138ea24ae34e90e248]  
  script: |
    docker info
    docker build -t %CIRRUS_REPO_FULL_NAME%:windows . -f Dockerfile.windows
    docker login --username=%DOCKERHUB_USER% --password=%DOCKERHUB_PASS% 
    docker push %CIRRUS_REPO_FULL_NAME%:windows    
  
linux_docker_builder:
  env:
    DOCKERHUB_USER: ENCRYPTED[80c86842f51e89eebd33a709eda8406f47194be550338b4eb04ac307c03c67b1f30bbc82032f58aeb86dbc0f1e8752ff]
    DOCKERHUB_PASS: ENCRYPTED[8c8912da52400d309e2fb75444639dfe774b210feaa5f1701e7a3f6e37959971ba41f9e5845c77138ea24ae34e90e248]  
  script: |
    docker info
    docker build -t $CIRRUS_REPO_FULL_NAME:linux . -f Dockerfile.linux
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker push $CIRRUS_REPO_FULL_NAME:linux
    
rpi_docker_builder:
  env:
    DOCKERHUB_USER: ENCRYPTED[80c86842f51e89eebd33a709eda8406f47194be550338b4eb04ac307c03c67b1f30bbc82032f58aeb86dbc0f1e8752ff]
    DOCKERHUB_PASS: ENCRYPTED[8c8912da52400d309e2fb75444639dfe774b210feaa5f1701e7a3f6e37959971ba41f9e5845c77138ea24ae34e90e248]  
  script: | 
    docker info
    docker build -t $CIRRUS_REPO_FULL_NAME:rpi . -f Dockerfile.rpi
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker push $CIRRUS_REPO_FULL_NAME:rpi
  
publish_docker_builder:
  depends_on: 
    - rpi
    - linux
    - windows
  env:
    DOCKERHUB_USER: ENCRYPTED[80c86842f51e89eebd33a709eda8406f47194be550338b4eb04ac307c03c67b1f30bbc82032f58aeb86dbc0f1e8752ff]
    DOCKERHUB_PASS: ENCRYPTED[8c8912da52400d309e2fb75444639dfe774b210feaa5f1701e7a3f6e37959971ba41f9e5845c77138ea24ae34e90e248]
    DOCKER_CLI_EXPERIMENTAL: enabled
  script: | 
    docker info
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker manifest create --amend $CIRRUS_REPO_FULL_NAME:latest $CIRRUS_REPO_FULL_NAME:linux  $CIRRUS_REPO_FULL_NAME:rpi  $CIRRUS_REPO_FULL_NAME:windows
    docker manifest push $CIRRUS_REPO_FULL_NAME:latest -p
