windows_docker_builder:
  platform: windows
  os_version: 2019
  script: |
    docker info
    docker build -t %CIRRUS_REPO_FULL_NAME%:windows . -f Dockerfile.windows
  
linux_docker_builder:
  script: |
    docker info
    docker build -t $CIRRUS_REPO_FULL_NAME:linux . -f Dockerfile.linux

rpi_docker_builder:
  script: | 
    docker info
    docker build -t $CIRRUS_REPO_FULL_NAME:rpi . -f Dockerfile.rpi
  
publish_docker_builder:
  depends_on: 
    - rpi
    - linux
    - windows
  env:
    DOCKERHUB_USER: ENCRYPTED[ccd1af2835558f6b3e08fa3dd8ad95e7b3eaf3b83220433093d6335a3f4727f4c53c4053587d1594799e72e331d1017d]
    DOCKERHUB_PASS: ENCRYPTED[7b81d2ca7878761ea497619cae892e267c0e0fdee71d8ce48dcd4ba11b9351a9d3f2f781dce84a7f8aab92a278007509]
  script: | 
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
