windows_build:
  windows_container:
    image: cirrusci/windowsservercore
  task:
    script: docker build -t mpromonet/dockertest:windows . -f Dockerfile.windows
    
docker_builder:
  build_script: docker build -t mpromonet/dockertest:linux . -f Dockerfile.linux
