windows_build:
  windows_container:
    image: cirrusci/windowsservercore
  task:
    script: docker build -t mpromonet/dockertest:windows . -f Dockerfile.windows
    
linux_build:
  container:
    image: docker
  task:  
    script: docker build -t mpromonet/dockertest:linux . -f Dockerfile.linux
