image: gitlab/gitlab-runner:latest
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
          - docker build -t ${IMAGE_TAG}-windows . -f Dockerfile.windows
          - docker push ${IMAGE_TAG}-windows
          - docker build -t ${IMAGE_TAG}-linux . -f Dockerfile.linux
          - docker push ${IMAGE_TAG}-linux

