os:
  - linux
  - windows

language: c

script:
  - docker info
  - docker build -t $TRAVIS_REPO_SLUG:travis-$TRAVIS_OS_NAME . -f Dockerfile.$TRAVIS_OS_NAME
  - docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
  - docker push $TRAVIS_REPO_SLUG:travis-$TRAVIS_OS_NAME

jobs:
  include:
    - stage: deploy
      script:
        - mkdir $HOME/.docker
        - echo "{ \"experimental\": \"enabled\" }" >> $HOME/.docker/config.json
        - docker info
        - docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
        - docker manifest create $TRAVIS_REPO_SLUG:travis $TRAVIS_REPO_SLUG:travis-windows $TRAVIS_REPO_SLUG:travis-linux
        - docker manifest push $TRAVIS_REPO_SLUG:travis -p
