os:
  - linux
  - windows

language: c

script:
  - docker info
  - docker build -t mpromonet/dockertest:travis-$TRAVIS_OS_NAME . -f Dockerfile.$TRAVIS_OS_NAME
  - docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
  - docker mpromonet/dockertest:travis-$TRAVIS_OS_NAME

jobs:
  include:
    - stage: deploy
      script:
        - mkdir $HOME/.docker
        - echo "{ \"experimental\": \"enabled\" }" >> $HOME/.docker/config.json
        - docker info
        - docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
        - docker manifest create mpromonet/dockertest::travis mpromonet/dockertest::travis-windows mpromonet/dockertest:travis-linux
        - docker manifest push mpromonet/dockertest::travis -p
