version: 1.0.{build}
image: 
- Ubuntu
- Visual Studio 2017

environment:
  DOCKER_USER:
    secure: x9TrGhfASxIJGqdfTG6LHg==
  DOCKER_PASS:
    secure: 8A704idfyG3NBIoN4mx5VmOukFzwSphXRHpzuCdPc3E=
install:
  - docker version

build_script:
  - ps: echo "$env:PLATFORM"
  - sh: docker build -t mpromonet/dockertest . -f Dockerfile.linux
  - cmd: docker build -t mpromonet/dockertest . -f Dockerfile.windows

deploy_script:
  - ps: docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS" 2>&1
  - ps: docker push mpromonet/dockertest
