FROM debian as builder
WORKDIR /build
COPY . /build

RUN apt-get update && apt-get install --no-install-recommends -y make cmake g++ git \
    && echo "GIT:$(git describe --tags --always --dirty)" \
    && git fetch --tags \
    && echo "GIT:$(git describe --tags --always --dirty)" \
    && cmake . \
    && make

FROM debian
WORKDIR /app
COPY --from=builder /build/hello /app/
ENTRYPOINT [ "/app/hello" ]
