name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: info
      run: env
    - name: ref
      run: echo ${{github.ref}}

    - name: Upload
      if: contains('refs/tags', github.ref)
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: '*.exe'
